export const SEMESTER_SUBJECTS: Record<number, string[]> = {
  2: [
    "Applied Mathematics II",
    "Applied Physics II",
    "Applied Chemistry",
    "Electrical Science",
    "Manufacturing Processes",
    "Engineering Mechanics",
    "Programming in C",
    "Environmental Science",
  ],
  4: [
    "Theory of Computation",
    "Technical Writing",
    "Database Management System",
    "Programming in Java",
    "Probability Statistics and Linear Programming",
    "Circuits and Systems",
  ],
  6: [
    "Artificial Intelligence",
    "Programming in Python",
    "Advanced Java Programming",
    "Web Technologies",
    "Database Modelling and Design",
    "E-Commerce and M-Commerce",
    "Introduction to Internet of Things",
    "Statistics, Statistical Modelling & Data Analytics",
    "Software Project Management",
    "Principles of Management for Engineers",
    "Introduction to Information and Communication Theory",
    "Middleware Technologies",
    "Advanced Computer Architecture",
    "Analog and Digital Communications",
    "Software Measurements, Metrics and Modelling",
    "Introduction to Digital Signal Processing",
    "Visual Basic.NET Programming",
    "Universal Human Values",
  ],
};
